CREATE TABLE IF NOT EXISTS vpn_peers (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    server_id VARCHAR(36) NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    public_key VARCHAR(255) NOT NULL UNIQUE,
    private_key VARCHAR(255) NOT NULL,
    ip VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
